-- MySQL Script generated by MySQL Workbench
-- Sun Feb  1 19:27:16 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tabela de serviços`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tabela de serviços` (
  `idtabela de serviços` INT NOT NULL,
  `descrição` VARCHAR(250) NULL,
  `valor` DECIMAL(13,2) NULL,
  PRIMARY KEY (`idtabela de serviços`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = ascii;


-- -----------------------------------------------------
-- Table `mydb`.`mecanico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mecanico` (
  `idmecanico` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `endereço` VARCHAR(250) NULL,
  `especialidade` VARCHAR(45) NULL,
  `tabela de serviços_idtabela de serviços` INT NOT NULL,
  PRIMARY KEY (`idmecanico`, `tabela de serviços_idtabela de serviços`),
  INDEX `fk_mecanico_tabela de serviços1_idx` (`tabela de serviços_idtabela de serviços` ASC) VISIBLE,
  CONSTRAINT `fk_mecanico_tabela de serviços1`
    FOREIGN KEY (`tabela de serviços_idtabela de serviços`)
    REFERENCES `mydb`.`tabela de serviços` (`idtabela de serviços`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `identificação` VARCHAR(18) NULL,
  `telefone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `endereço` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`veiculo` (
  `idveiculo` INT NOT NULL AUTO_INCREMENT,
  `veiculo` VARCHAR(45) NULL,
  `marca` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  `ano` INT NULL,
  `combustivel` VARCHAR(45) NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idveiculo`, `Cliente_idCliente`),
  INDEX `fk_veiculo_Cliente_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_veiculo_Cliente`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`equipe` (
  `idequipe` INT NOT NULL,
  PRIMARY KEY (`idequipe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ordem de serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ordem de serviço` (
  `idordem de serviço` INT NOT NULL AUTO_INCREMENT,
  `emissão` DATE NULL,
  `valor` DECIMAL(13,2) NULL,
  `status` TINYINT NULL,
  `ordem de serviço_idordem de serviço` INT NOT NULL,
  `veiculo_idveiculo` INT NOT NULL,
  `veiculo_Cliente_idCliente` INT NOT NULL,
  `equipe_idequipe` INT NOT NULL,
  `conclusão` DATE NULL,
  PRIMARY KEY (`idordem de serviço`, `ordem de serviço_idordem de serviço`, `veiculo_idveiculo`, `veiculo_Cliente_idCliente`, `equipe_idequipe`),
  UNIQUE INDEX `data de emissão_UNIQUE` (`emissão` ASC) VISIBLE,
  INDEX `fk_ordem de serviço_veiculo1_idx` (`veiculo_idveiculo` ASC, `veiculo_Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_ordem de serviço_equipe1_idx` (`equipe_idequipe` ASC) VISIBLE,
  CONSTRAINT `fk_ordem de serviço_veiculo1`
    FOREIGN KEY (`veiculo_idveiculo` , `veiculo_Cliente_idCliente`)
    REFERENCES `mydb`.`veiculo` (`idveiculo` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordem de serviço_equipe1`
    FOREIGN KEY (`equipe_idequipe`)
    REFERENCES `mydb`.`equipe` (`idequipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mecanico_has_ordem de serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mecanico_has_ordem de serviço` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`equipe_has_mecanico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`equipe_has_mecanico` (
  `equipe_idequipe` INT NOT NULL,
  `mecanico_idmecanico` INT NOT NULL,
  `mecanico_tabela de serviços_idtabela de serviços` INT NOT NULL,
  PRIMARY KEY (`equipe_idequipe`, `mecanico_idmecanico`, `mecanico_tabela de serviços_idtabela de serviços`),
  INDEX `fk_equipe_has_mecanico_mecanico1_idx` (`mecanico_idmecanico` ASC, `mecanico_tabela de serviços_idtabela de serviços` ASC) VISIBLE,
  INDEX `fk_equipe_has_mecanico_equipe1_idx` (`equipe_idequipe` ASC) VISIBLE,
  CONSTRAINT `fk_equipe_has_mecanico_equipe1`
    FOREIGN KEY (`equipe_idequipe`)
    REFERENCES `mydb`.`equipe` (`idequipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipe_has_mecanico_mecanico1`
    FOREIGN KEY (`mecanico_idmecanico` , `mecanico_tabela de serviços_idtabela de serviços`)
    REFERENCES `mydb`.`mecanico` (`idmecanico` , `tabela de serviços_idtabela de serviços`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tabela de serviços_has_ordem de serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tabela de serviços_has_ordem de serviço` (
  `tabela de serviços_idtabela de serviços` INT NOT NULL,
  `ordem de serviço_idordem de serviço` INT NOT NULL,
  `ordem de serviço_ordem de serviço_idordem de serviço` INT NOT NULL,
  `ordem de serviço_veiculo_idveiculo` INT NOT NULL,
  `ordem de serviço_veiculo_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`tabela de serviços_idtabela de serviços`, `ordem de serviço_idordem de serviço`, `ordem de serviço_ordem de serviço_idordem de serviço`, `ordem de serviço_veiculo_idveiculo`, `ordem de serviço_veiculo_Cliente_idCliente`),
  INDEX `fk_tabela de serviços_has_ordem de serviço_ordem de servi_idx` (`ordem de serviço_idordem de serviço` ASC, `ordem de serviço_ordem de serviço_idordem de serviço` ASC, `ordem de serviço_veiculo_idveiculo` ASC, `ordem de serviço_veiculo_Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_tabela de serviços_has_ordem de serviço_tabela de serv_idx` (`tabela de serviços_idtabela de serviços` ASC) VISIBLE,
  CONSTRAINT `fk_tabela de serviços_has_ordem de serviço_tabela de servi1`
    FOREIGN KEY (`tabela de serviços_idtabela de serviços`)
    REFERENCES `mydb`.`tabela de serviços` (`idtabela de serviços`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tabela de serviços_has_ordem de serviço_ordem de serviço1`
    FOREIGN KEY (`ordem de serviço_idordem de serviço` , `ordem de serviço_ordem de serviço_idordem de serviço` , `ordem de serviço_veiculo_idveiculo` , `ordem de serviço_veiculo_Cliente_idCliente`)
    REFERENCES `mydb`.`ordem de serviço` (`idordem de serviço` , `ordem de serviço_idordem de serviço` , `veiculo_idveiculo` , `veiculo_Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = ascii;


-- -----------------------------------------------------
-- Table `mydb`.`peças`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`peças` (
  `idpeças` INT NOT NULL,
  `codigo` VARCHAR(45) NULL,
  `descrição` VARCHAR(250) NULL,
  `valor` DECIMAL(13,2) NULL,
  `peçascol` VARCHAR(45) NULL,
  PRIMARY KEY (`idpeças`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`peças_has_ordem de serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`peças_has_ordem de serviço` (
  `peças_idpeças` INT NOT NULL,
  `ordem de serviço_idordem de serviço` INT NOT NULL,
  `ordem de serviço_ordem de serviço_idordem de serviço` INT NOT NULL,
  `ordem de serviço_veiculo_idveiculo` INT NOT NULL,
  `ordem de serviço_veiculo_Cliente_idCliente` INT NOT NULL,
  `quantidade` INT NULL,
  PRIMARY KEY (`peças_idpeças`, `ordem de serviço_idordem de serviço`, `ordem de serviço_ordem de serviço_idordem de serviço`, `ordem de serviço_veiculo_idveiculo`, `ordem de serviço_veiculo_Cliente_idCliente`),
  INDEX `fk_peças_has_ordem de serviço_ordem de serviço1_idx` (`ordem de serviço_idordem de serviço` ASC, `ordem de serviço_ordem de serviço_idordem de serviço` ASC, `ordem de serviço_veiculo_idveiculo` ASC, `ordem de serviço_veiculo_Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_peças_has_ordem de serviço_peças1_idx` (`peças_idpeças` ASC) VISIBLE,
  CONSTRAINT `fk_peças_has_ordem de serviço_peças1`
    FOREIGN KEY (`peças_idpeças`)
    REFERENCES `mydb`.`peças` (`idpeças`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_peças_has_ordem de serviço_ordem de serviço1`
    FOREIGN KEY (`ordem de serviço_idordem de serviço` , `ordem de serviço_ordem de serviço_idordem de serviço` , `ordem de serviço_veiculo_idveiculo` , `ordem de serviço_veiculo_Cliente_idCliente`)
    REFERENCES `mydb`.`ordem de serviço` (`idordem de serviço` , `ordem de serviço_idordem de serviço` , `veiculo_idveiculo` , `veiculo_Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
